require "test_helper"

module Source::Tests::URL
  class NullTest < ActiveSupport::TestCase
    context "determining the site name" do
      should "work" do
        assert_equal("Foo", Source::URL.parse("https://foo.com.").site_name)
        assert_equal("Foo", Source::URL.parse("https://user:pass@foo.com:80").site_name)
        assert_equal("Localhost", Source::URL.parse("https://localhost").site_name)
        assert_equal("127.0.0.1", Source::URL.parse("https://127.0.0.1").site_name)
        assert_equal("127.0.0.1:3000", Source::URL.parse("https://127.0.0.1:3000").site_name)
        assert_equal("[::1]", Source::URL.parse("https://[::1]").site_name)
        assert_equal("[::1]:3000", Source::URL.parse("https://[::1]:3000").site_name)
      end

      should "work for a known site" do
        assert_equal("Amino", Source::URL.parse("https://aminoapps.com/u/SequelUncut").site_name)
        assert_equal("AniList", Source::URL.parse("https://anilist.co/user/Megumon").site_name)
        assert_equal("Apple Music", Source::URL.parse("https://music.apple.com/artist/1626455561").site_name)
        assert_equal("Archive of Our Own", Source::URL.parse("https://archiveofourown.org/users/ari1654").site_name)
        assert_equal("Art Fight", Source::URL.parse("http://artfight.net/~OFUKITTY").site_name)
        assert_equal("Artists&Clients", Source::URL.parse("https://artistsnclients.com/people/sbong2").site_name)
        assert_equal("Bandcamp", Source::URL.parse("https://pigmhall.bandcamp.com").site_name)
        assert_equal("Big Cartel", Source::URL.parse("https://quintzeee.bigcartel.com").site_name)
        assert_equal("Blogger", Source::URL.parse("http://chiizupan.blogspot.com").site_name)
        assert_equal("Buy Me a Coffee", Source::URL.parse("https://www.buymeacoffee.com/sasimekk42").site_name)
        assert_equal("Circle.ms", Source::URL.parse("https://portal.circle.ms/Circle/Index/10084525").site_name)
        assert_equal("Class101", Source::URL.parse("https://class101.net/products/315Q19v2UzhkELv2X4Xa").site_name)
        assert_equal("Colors Live", Source::URL.parse("https://www.colorslive.com/artist/nasubino").site_name)
        assert_equal("Curious Cat", Source::URL.parse("https://curiouscat.live/LOPPromptbot").site_name)
        assert_equal("Danbooru", Source::URL.parse("https://danbooru.donmai.us/users/1176221").site_name)
        assert_equal("Doujinshi.org", Source::URL.parse("http://www.doujinshi.org/browse/author/92838/Ojo").site_name)
        assert_equal("Doujinshi.org", Source::URL.parse("http://doujinshi.mugimugi.org/browse/author/47832/MisRoma/").site_name)
        assert_equal("E-Hentai", Source::URL.parse("https://e-hentai.org/uploader/Laundrymom").site_name)
        assert_equal("Excite Blog", Source::URL.parse("http://spzinno.exblog.jp").site_name)
        assert_equal("FanFiction.Net", Source::URL.parse("https://www.fanfiction.net/u/1795942").site_name)
        assert_equal("GitHub", Source::URL.parse("https://github.com/Shimofumi").site_name)
        assert_equal("Gunsta", Source::URL.parse("https://gumpla.jp/author/Salty_GUNPLA").site_name)
        assert_equal("Hatena", Source::URL.parse("http://d.hatena.ne.jp/yuutamiitan/").site_name)
        assert_equal("Hatena Blog", Source::URL.parse("http://yeaththekid.hatenablog.com").site_name)
        assert_equal("html.co.jp", Source::URL.parse("https://html.co.jp/zeelch").site_name)
        assert_equal("Itch.io", Source::URL.parse("https://lewdwayne.itch.io").site_name)
        assert_equal("Line", Source::URL.parse("https://store.line.me/stickershop/author/103126").site_name)
        assert_equal("LinkedIn", Source::URL.parse("https://www.linkedin.com/in/star-ren/").site_name)
        assert_equal("7-Eleven MyShip", Source::URL.parse("https://myship.7-11.com.tw/general/detail/GM2311291644399").site_name)
        assert_equal("Bahamut", Source::URL.parse("https://home.gamer.com.tw/homeindex.php?owner=zxc16978").site_name)
        assert_equal("BASE", Source::URL.parse("https://tsukiakari09.theshop.jp").site_name)
        assert_equal("BASE", Source::URL.parse("https://artistname.thebase.com").site_name)
        assert_equal("Cash App", Source::URL.parse("https://cash.app/$artistname").site_name)
        assert_equal("Clibo", Source::URL.parse("https://cli-bo.com/user/abc").site_name)
        assert_equal("Comic Vine", Source::URL.parse("https://comicvine.gamespot.com/profile/artist").site_name)
        assert_equal("Commiss.io", Source::URL.parse("https://commiss.io/artistname").site_name)
        assert_equal("Direct.me", Source::URL.parse("https://direct.me/artist").site_name)
        assert_equal("Drawcrowd", Source::URL.parse("https://dxthpu4318olx.cloudfront.net/users/agussw").site_name)
        assert_equal("Eth.co", Source::URL.parse("https://eth.co/artist").site_name)
        assert_equal("Final Fantasy XIV", Source::URL.parse("https://na.finalfantasyxiv.com/lodestone/character/1234").site_name)
        assert_equal("GameFAQs", Source::URL.parse("https://gamefaqs.gamespot.com/community/artist").site_name)
        assert_equal("Gank", Source::URL.parse("https://www.ganknow.com/artist").site_name)
        assert_equal("Image Comics", Source::URL.parse("https://imagecomics.com/creators/view/artist").site_name)
        assert_equal("img.ly", Source::URL.parse("http://img.ly/images/ermame26").site_name)
        assert_equal("Instabio", Source::URL.parse("https://instabio.cc/artist").site_name)
        assert_equal("Instabio", Source::URL.parse("https://linkbio.co/artist").site_name)
        assert_equal("Kemono Party", Source::URL.parse("https://kemono.party/patreon/user/123").site_name)
        assert_equal("Kirby's Comic Art", Source::URL.parse("https://www.kirbyscomicart.com/artist").site_name)
        assert_equal("Kiru Made", Source::URL.parse("https://kirumade.com/artist").site_name)
        assert_equal("Last.fm", Source::URL.parse("https://www.last.fm/user/artist").site_name)
        assert_equal("Lava.top", Source::URL.parse("https://lava.top/@artist").site_name)
        assert_equal("League of Comic Geeks", Source::URL.parse("https://leagueofcomicgeeks.com/profile/artist").site_name)
        assert_equal("Livedoor", Source::URL.parse("https://blog.livedoor.jp/ac370ml").site_name)
        assert_equal("Livedoor", Source::URL.parse("https://livedoor.livedoor.biz/archives/artist.html").site_name)
        assert_equal("Lit.link", Source::URL.parse("https://lit.link/en/artist").site_name)
        assert_equal("Manga Library Z", Source::URL.parse("https://www.mangaz.com/person/detail/44761").site_name)
        assert_equal("Mangano", Source::URL.parse("https://manga-no.com/artist/123").site_name)
        assert_equal("MarppleShop", Source::URL.parse("https://marpple.shop/kr/@artist").site_name)
        assert_equal("Mastodon", Source::URL.parse("https://mastodon.cloud/@artist").site_name)
        assert_equal("Mastodon", Source::URL.parse("https://mstdn.jp/@oneb").site_name)
        assert_equal("Milkshake", Source::URL.parse("https://msha.ke/artist").site_name)
        assert_equal("Milkshake", Source::URL.parse("https://milkshake.app/artist").site_name)
        assert_equal("MyAnimeList", Source::URL.parse("https://myanimelist.net/profile/artist").site_name)
        assert_equal("MyFigureCollection", Source::URL.parse("https://myfigurecollection.net/profile/artist").site_name)
        assert_equal("OCN", Source::URL.parse("http://homepage3.ocn.ne.jp/~artist").site_name)
        assert_equal("OnlyFans", Source::URL.parse("https://onlyfans.com/artist").site_name)
        assert_equal("Ou Xiang Xie Zhen", Source::URL.parse("https://www.ouxiangxiezhen.com/artist").site_name)
        assert_equal("Overdoll", Source::URL.parse("https://overdoll.com/artist").site_name)
        assert_equal("Overdoll", Source::URL.parse("https://dollycdn.net/artist").site_name)
        assert_equal("PayPal", Source::URL.parse("https://www.paypal.me/artist").site_name)
        assert_equal("PayPal", Source::URL.parse("https://www.paypal.com/donate/?hosted_button_id=ABC").site_name)
        assert_equal("Pixel Joint", Source::URL.parse("https://pixeljoint.com/p/artist.htm").site_name)
        assert_equal("Planet Minecraft", Source::URL.parse("https://www.planetminecraft.com/member/artist").site_name)
        assert_equal("Pronouns.page", Source::URL.parse("https://en.pronouns.page/@artist").site_name)
        assert_equal("Pronouny.xyz", Source::URL.parse("https://pronouny.xyz/u/artist").site_name)
        assert_equal("Joyreactor", Source::URL.parse("https://joyreactor.cc/user/artist").site_name)
        assert_equal("Joyreactor", Source::URL.parse("https://reactor.cc/user/artist").site_name)
        assert_equal("Jump Rookie!", Source::URL.parse("https://rookie.shonenjump.com/author/artist").site_name)
        assert_equal("Sakura.ne.jp", Source::URL.parse("https://www117.sakura.ne.jp/~artist").site_name)
        assert_equal("Scratch", Source::URL.parse("https://scratch.mit.edu/users/artist").site_name)
        assert_equal("Secret Drawing Box", Source::URL.parse("https://drawme.share-on.me/artist").site_name)
        assert_equal("Sheezy.art", Source::URL.parse("https://sheezy.art/artist").site_name)
        assert_equal("Solo.to", Source::URL.parse("https://solo.to/artist").site_name)
        assert_equal("SoundCloud", Source::URL.parse("https://soundcloud.com/artist").site_name)
        assert_equal("Spotify", Source::URL.parse("https://open.spotify.com/artist/123").site_name)
        assert_equal("Square", Source::URL.parse("https://artist.square.site").site_name)
        assert_equal("Square", Source::URL.parse("https://squareup.com/store/artist").site_name)
        assert_equal("Steam", Source::URL.parse("https://steamcommunity.com/id/artist").site_name)
        assert_equal("Straw.page", Source::URL.parse("https://straw.page/artist").site_name)
        assert_equal("SubscribeStar", Source::URL.parse("https://subscribestar.adult/artist").site_name)
        assert_equal("SubscribeStar", Source::URL.parse("https://subscribestar.com/artist").site_name)
        assert_equal("SuperRare", Source::URL.parse("https://superrare.com/artist").site_name)
        assert_equal("Suzuri", Source::URL.parse("https://suzuri.jp/artist").site_name)
        assert_equal("Suzuri", Source::URL.parse("https://dijsur42hqnz1.cloudfront.net/products/artist").site_name)
        assert_equal("Taiwan Doujinshi Center", Source::URL.parse("https://shop.doujin.com.tw/artist").site_name)
        assert_equal("Tapas", Source::URL.parse("https://tapas.io/artist").site_name)
        assert_equal("Tapas", Source::URL.parse("https://d30womf5coomej.cloudfront.net/artist").site_name)
        assert_equal("TeePublic", Source::URL.parse("https://www.teepublic.com/user/artist").site_name)
        assert_equal("Telegram", Source::URL.parse("https://t.me/artist").site_name)
        assert_equal("Telegram", Source::URL.parse("https://telegram.org/artist").site_name)
        assert_equal("TensorArt", Source::URL.parse("https://tensor.art/u/artist").site_name)
        assert_equal("The Interviews", Source::URL.parse("http://theinterviews.jp/artist").site_name)
        assert_equal("Tistory", Source::URL.parse("https://artist.tistory.com").site_name)
        assert_equal("Toyhouse", Source::URL.parse("https://toyhou.se/artist").site_name)
        assert_equal("Trello", Source::URL.parse("https://bxp-content-static.prod.public.atl-paas.net/board-bg.jpg").site_name)
        assert_equal("tsunagu.cloud", Source::URL.parse("https://tsunagu.cloud/artist").site_name)
        assert_equal("Vimeo", Source::URL.parse("https://vimeo.com/artist").site_name)
        assert_equal("Vimeo", Source::URL.parse("https://livestream.com/artist").site_name)
        assert_equal("Webtoons", Source::URL.parse("https://www.webtoons.com/en/creator/artist").site_name)
        assert_equal("Weebly", Source::URL.parse("https://artist.weebly.com").site_name)
        assert_equal("Weebly", Source::URL.parse("https://artist.weeblysite.com").site_name)
        assert_equal("Willow", Source::URL.parse("https://wlo.link/@artist").site_name)
        assert_equal("Wix", Source::URL.parse("https://artist.wixsite.com/home").site_name)
        assert_equal("Wix", Source::URL.parse("https://static.wixstatic.com/media/artist.jpg").site_name)
        assert_equal("WordPress", Source::URL.parse("https://artist.wordpress.com").site_name)
        assert_equal("Ameba", Source::URL.parse("https://www.ameba.jp/artist").site_name)
        assert_equal("Booru.org", Source::URL.parse("https://img.booru.org/drawfriends/images/36/de65.jpg").site_name)
        assert_equal("Comiczin", Source::URL.parse("https://shop.comiczin.jp/products/list.php?category_id=3394").site_name)
        assert_equal("Dropbox", Source::URL.parse("https://www.dropbox.com/sh/gz9/GHt_oHDKsR").site_name)
        assert_equal("Nanos", Source::URL.parse("https://nanos.jp/artist").site_name)
        assert_equal("Pomf", Source::URL.parse("https://pomf.tv/artist").site_name)
        assert_equal("SmutBase", Source::URL.parse("https://smutba.se/artist").site_name)
        assert_equal("Tegaki", Source::URL.parse("https://tegaki.com/user/artist").site_name)
        assert_equal("YCH.art", Source::URL.parse("https://ych.art/user/artist").site_name)
        assert_equal("Youtube", Source::URL.parse("https://youtu.be/dQw4w9WgXcQ").site_name)
      end
    end

    context "For unknown sources" do
      should "leave them as they are" do
        assert_nil(Source::URL.page_url("https://google.com"))
        assert_nil(Source::URL.page_url("a bad non-http source"))
        assert_nil(Source::URL.page_url("https://example.com/Folder/中央大学.html"))
      end
    end

    context "The bad_source? method" do
      should "not treat recognized but unhandled sites as bad sources" do
        assert_not(Source::URL.parse("https://www.etsy.com/shop/yeurei").bad_source?)
        assert_not(Source::URL.parse("https://i.etsystatic.com/isbl/ef769d/65460303/isbl_3360x840.65460303_idqpnurw.jpg").bad_source?)
      end
    end

    context "The bad_link? method" do
      should "not treat recognized but unhandled sites as bad links" do
        assert_not(Source::URL.parse("https://www.etsy.com/shop/yeurei").bad_link?)
        assert_not(Source::URL.parse("https://i.etsystatic.com/isbl/ef769d/65460303/isbl_3360x840.65460303_idqpnurw.jpg").bad_link?)
      end
    end

    should parse_url("https://foo.com.").into(site_name: "Foo")
  end
end
