version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
