# https://docs.rubocop.org/rubocop/latest/configuration.html
# https://docs.rubocop.org/rubocop-factory_bot/latest/cops_factorybot.html
#
# Ruby: https://rubystyle.guide/
# Rails: https://rails.rubystyle.guide/
# Airbnb: https://github.com/airbnb/ruby
# Gitlab: https://docs.gitlab.com/development/backend/ruby_style_guide/
# Shopify: https://ruby-style-guide.shopify.dev/
plugins:
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  ActiveSupportExtensionsEnabled: true
  StringLiteralsFrozenByDefault: true
  SuggestExtensions: false
  Exclude:
    - "node_modules/**/*"
    - "public/**/*"
    - "script/**/*"
    - "tmp/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/test/**/*"

Lint/DuplicateBranch:
  Enabled: false

Lint/SymbolConversion:
  EnforcedStyle: consistent

Lint/UselessAssignment:
  Exclude:
    - "**/test/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 400
  Exclude:
    - "**/test/**/*"

Metrics/BlockNesting:
  CountBlocks: false
  Max: 4

Metrics/ClassLength:
  Max: 750
  Exclude:
    - "**/test/**/*"

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 250

Metrics/ModuleLength:
  Max: 400

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 100

Lint/InheritException:
  EnforcedStyle: standard_error

Naming/BlockForwarding:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Rails/Blank:
  UnlessPresent: false

Rails/DynamicFindBy:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HttpStatus:
  EnforcedStyle: numeric

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ArgumentsForwarding:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 20

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  AllowedPatterns:
  - \d{4}(_\d{4})*

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "default": "{}"
    "%i": "[]"
    "%I": "[]"
    "%w": "[]"
    "%W": "[]"
    "%r": "{}"

Style/ParallelAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: false

Style/SafeNavigationChainLength:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  MinSize: 10

Style/SymbolProc:
  AllowedMethods:
    - respond_with

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/WordArray:
  MinSize: 10
