---
include:
- "**/*.rb"
exclude:
- test/**/*
require: []
domains: []
reporters:
- rubocop
- require_not_found
- typecheck:typed
- update_errors
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins: []
max_files: 5000
