# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: dtext_rb 1.0.14 ruby lib
# stub: ext/dtext/extconf.rb

Gem::Specification.new do |s|
  s.name = "dtext_rb"
  s.version = "1.0.14"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["r888888888"]
  s.date = "2016-09-23"
  s.description = "Compield DText parser"
  s.email = "r888888888@gmail.com"
  s.extensions = ["ext/dtext/extconf.rb"]
  s.files = [
    ".rbenv-version",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "VERSION",
    "dtext_rb.gemspec",
    "ext/dtext/dtext.c",
    "ext/dtext/dtext.h",
    "ext/dtext/dtext.rl",
    "ext/dtext/extconf.rb",
    "lib/dtext.rb",
    "lib/dtext_ruby.rb",
    "test/dtext_test.rb",
    "test/ragel_output.txt",
    "test/test_forum_posts.rb",
    "test/test_wiki_pages.rb",
    "test/wiki.txt"
  ]
  s.homepage = "http://github.com/r888888888/dtext_rb"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Compiled DText parser"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<minitest>, ["~> 5.8"])
      s.add_runtime_dependency(%q<rake-compiler>, ["~> 0.9"])
      s.add_runtime_dependency(%q<jeweler>, ["~> 2.0"])
    else
      s.add_dependency(%q<minitest>, ["~> 5.8"])
      s.add_dependency(%q<rake-compiler>, ["~> 0.9"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<minitest>, ["~> 5.8"])
    s.add_dependency(%q<rake-compiler>, ["~> 0.9"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
  end
end

