# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

CLEAN.include FileList["**/*.{so,o}", "ext/dtext/Makefile", "pkg"]

Rake::TestTask.new(:test) do |t|
  t.test_files = FileList["test/**/test_*.rb"]
end

task bench: :compile do
  require_relative "test/bench_dtext"
end

file "lib/dtext/dtext.so" => FileList["ext/dtext/*.{cpp,rl,h}"] do
  system "cd ext/dtext && ruby extconf.rb && make && mv dtext.so ../../lib/dtext"
end

task compile: "lib/dtext/dtext.so"
task build: :compile
task test: :compile
task default: :test
