# frozen_string_literal: true

# ENV["G_MESSAGES_DEBUG"] = "all"

require "bundler/gem_tasks"
require "rake/testtask"

CLEAN.include FileList["**/*.{so,o}", "ext/dtext/Makefile", "bin/cdtext.exe", "pkg"]

#task compile: "bin/cdtext.exe"
#file "bin/cdtext.exe" => "ext/dtext/dtext.cpp" do
#  flags = "#{ENV["CFLAGS"] || "-std=c++20 -ggdb3 -pg -Wall -Wno-unused-const-variable"}"
#  libs = "$(pkg-config --cflags --libs glib-2.0)"
#  sh "g++ -DCDTEXT -o bin/cdtext.exe ext/dtext/dtext.cpp #{flags} #{libs}"
#end

Rake::TestTask.new(:test) do |t|
  t.test_files = FileList["test/**/test_*.rb"]
end

task bench: :compile do
  require_relative "test/bench_dtext"
end

file "lib/dtext/dtext.so" => FileList["ext/dtext/*.{cpp,rl,h}"] do
  system "cd ext/dtext && ruby extconf.rb && make && mv dtext.so ../../lib/dtext"
end

task compile: "lib/dtext/dtext.so"
task build: :compile
task test: :compile
task default: :test
