FROM postgres:latest

RUN apt-get update && apt-get -y install build-essential git postgresql-server-dev-all

RUN rm -rf /test_parser
WORKDIR /test_parser
RUN git clone https://github.com/r888888888/test_parser . && make install
