#!/usr/bin/env sh

mkdir -p public/javascripts/compiled/posts

cat public/javascripts/src/lib/jquery.min.js > public/javascripts/compiled/default.js
cat public/javascripts/src/lib/jquery-ui-1.8.5.custom.min.js >> public/javascripts/compiled/default.js
cat public/javascripts/src/lib/jrails.min.js >> public/javascripts/compiled/default.js
cat public/javascripts/src/lib/rails.js >> public/javascripts/compiled/default.js
cat public/javascripts/src/app/cookie.js >> public/javascripts/compiled/default.js
cat public/javascripts/src/app/application.js >> public/javascripts/compiled/default.js
cat public/javascripts/src/app/posts.js >> public/javascripts/compiled/default.js
cat public/javascripts/src/app/comments.js >> public/javascripts/compiled/default.js
cat public/javascripts/src/app/uploads.js >> public/javascripts/compiled/default.js
cat public/javascripts/src/app/users.js >> public/javascripts/compiled/default.js
