#!/bin/bash

# This file is used to add the Git commit hash to the Docker image when the
# image is built by Docker Hub.
#
# https://docs.docker.com/docker-hub/builds/advanced/
# https://stackoverflow.com/questions/59057978/passing-source-commit-to-dockerfile-commands-on-docker-hub
#
# SOURCE_COMMIT: the SHA1 hash of the commit being tested.
# DOCKERFILE_PATH: the dockerfile currently being built.
# IMAGE_NAME: the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:DOCKER_TAG.)

docker build --build-arg SOURCE_COMMIT=$SOURCE_COMMIT -f $DOCKERFILE_PATH -t $IMAGE_NAME .
